# Generated by Django 4.2.7 on 2023-12-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Жанр')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('photo', models.ImageField(upload_to='groups/', verbose_name='Photo')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('created_date', models.DateField(verbose_name='Дата создания группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группа',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя певца')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия певца')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Псевдоним')),
                ('photo', models.ImageField(upload_to='singers/', verbose_name='Photo')),
                ('biography', models.TextField(verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Певец',
                'verbose_name_plural': 'Певец',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название музыки')),
                ('public_date', models.DateField(verbose_name='Дата выпуска песни')),
                ('text_song', models.TextField(verbose_name='Текст песни')),
                ('music', models.FileField(upload_to='music/', verbose_name='Музыка')),
                ('genre', models.ManyToManyField(related_name='music_genre', to='music.genre', verbose_name='Жанр песни')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_group', to='music.group', verbose_name='Группа')),
                ('singer', models.ManyToManyField(related_name='singer_music', to='music.singer', verbose_name='Певец')),
            ],
            options={
                'verbose_name': 'Музыка',
                'verbose_name_plural': 'Музыка',
                'ordering': ['-public_date'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='singer',
            field=models.ManyToManyField(related_name='singer_group', to='music.singer', verbose_name='Певец'),
        ),
    ]
